-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1tUWcSvepouJBhc5Wiy+ovbRasRYtI3+RqKCCH2c9vegCgYIKoZIzj0DAQehRANCAAQPmdkGfjezks8q4AoSk5FhtcDi10wozTQKkSzaCeg2azibOkWZnuprGakmaj82owk5EIe4mH6ZROJPZTcp2scW
-----END PRIVATE KEY-----